print("a" + "b")
print("hola"+str(5))
print(str(5) + "hola")
print([1, 2] + [3, 4])
print("hola" + str([1,2,3]))
print(5.3 + 5)
print(True + False)
print(True + True)
print(False + False)
print(False + True)